// /** @type {import('tailwindcss').Config} */

const { fontFamily } = require("tailwindcss/defaultTheme");

module.exports = {
    content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
    theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1028px",
            xl: "1536px",
            "2xl": "1640px",
        },
        container: {
            sm: "100%",
            md: "960px",
            lg: "1024px",
            xl: "1440px",
            "2xl": "calc((100vw - 1680px) / 2)",
        },
        extend: {
            fontFamily: {
                ...fontFamily,
                sans: ["Montserrat", "sans-serif"],
                pantonextrabold: ["pantonextrabold", "sans-serif"],
                pantonextralight: ["pantonextralight", "sans-serif"],
                pantonheavy: ["pantonheavy", "sans-serif"],
                pantonlight: ["pantonlight", "sans-serif"],
                pantonregular: ["pantonregular", "sans-serif"],
                pantonsemibold: ["pantonsemibold", "sans-serif"],
                pantonbold: ["pantonbold", "sans-serif"],
                pantonblack: ["pantonblack", "sans-serif"],
                pantonthin: ["pantonthin", "sans-serif"],
            },
            colors: {
                primaryColor: {
                    DEFAULT: "#da5a94",
                    50: "#fcf3f8",
                    100: "#fae9f2",
                    200: "#f6d4e6",
                    300: "#f0b1d1",
                    400: "#e88bb8",
                    500: "#da5a94",
                    600: "#c73b74",
                    700: "#ac2a5b",
                    800: "#8e264c",
                    900: "#772442",
                    950: "#480f24",
                },
                secondaryColor: {
                    DEFAULT: "#7da43e",
                    50: "#f5f9ec",
                    100: "#e8f1d6",
                    200: "#d4e5b1",
                    300: "#b7d284",
                    400: "#9bbf5d",
                    500: "#7da43e",
                    600: "#60822e",
                    700: "#4b6427",
                    800: "#3d5024",
                    900: "#354522",
                    950: "#1a250e",
                },
                darkText: "#4C4D4F",
                darkBG: "#1B1B1C",
                bg: "#FBFBF5",
                redColor: "#FE654F",
                greenColor: "#61E8E1",
                darkRed: "#444140",
            },
        },
    },
    plugins: [],
};
